project:
  type: website
  output-dir: docs
website:
  title: "Bioconductor Website Redesign"
  navbar:
    right:
      - icon: github
        href: https://github.com/mblue9/biocwebsite
        aria-label: GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true